// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Generate sidebar automatically based on docs from dirname
  // More info about how to customize this sidebar: https://docusaurus.io/docs/sidebar
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
